---
#
# http://docs.ansible.com/ansible/lineinfile_module.html
#

- name: copy .gitconfig file to guest VM
  action: template src=templates/.gitconfig dest=~/.gitconfig

- name: load .prompt file from .profile
  lineinfile:
    dest: ~/.profile
    line: ". /vagrant/playbooks/templates/.prompt"
