---
- hosts: betterlists-vm
  user: vagrant

  # http://docs.ansible.com/ansible/playbooks_lookups.html
  # http://docs.ansible.com/ansible/playbooks_filters.html
  vars:
    ruby_version_default: "{{ lookup('ini', 'RUBY_VERSION type=properties file=../.env') }}"
    ruby_version_local: "{{ lookup('ini', 'RUBY_VERSION type=properties file=../.env.local') }}"
    ruby_version: "{{ ruby_version_local | default(ruby_version_default, true) }}"

    app_name_default: "{{ lookup('ini', 'APP_NAME type=properties file=../.env') }}"
    app_name_local: "{{ lookup('ini', 'APP_NAME type=properties file=../.env.local') }}"
    app_name: "{{ app_name_local | default(app_name_default, true) }}"

    ssh_passphrase_default: "{{ lookup('ini', 'SSH_PASSPHRASE type=properties file=../.env') }}"
    ssh_passphrase_local: "{{ lookup('ini', 'SSH_PASSPHRASE type=properties file=../.env.local') }}"
    ssh_passphrase: "{{ ssh_passphrase_local | default(ssh_passphrase_default, true) }}"

    postgres_user_default: "{{ lookup('ini', 'POSTGRES_USER type=properties file=../.env') }}"
    postgres_user_local: "{{ lookup('ini', 'POSTGRES_USER type=properties file=../.env.local') }}"
    postgres_user: "{{ postgres_user_local | default(postgres_user_default, true) }}"

    postgres_password_default: "{{ lookup('ini', 'POSTGRES_PASSWORD type=properties file=../.env') }}"
    postgres_password_local: "{{ lookup('ini', 'POSTGRES_PASSWORD type=properties file=../.env.local') }}"
    postgres_password: "{{ postgres_password_local | default(postgres_password_default, true) }}"

    postgres_host_port_default: "{{ lookup('ini', 'POSTGRES_HOST_PORT type=properties file=../.env') }}"
    postgres_host_port_local: "{{ lookup('ini', 'POSTGRES_HOST_PORT type=properties file=../.env.local') }}"
    postgres_host_port: "{{ postgres_host_port_local | default(postgres_host_port_default, true) }}"

    api_db_user_default: "{{ lookup('ini', 'API_DB_USER type=properties file=../.env') }}"
    api_db_user_local: "{{ lookup('ini', 'API_DB_USER type=properties file=../.env.local') }}"
    api_db_user: "{{ api_db_user_local | default(api_db_user_default, true) }}"

    api_db_password_default: "{{ lookup('ini', 'API_DB_PASSWORD type=properties file=../.env') }}"
    api_db_password_local: "{{ lookup('ini', 'API_DB_PASSWORD type=properties file=../.env.local') }}"
    api_db_password: "{{ api_db_password_local | default(api_db_password_default, true) }}"

  tasks:
    - include: install_packages.yml
    - include: db_setup.yml
    - include: rvm_setup.yml
    - include: ssh_keys.yml
    - include: bash_setup.yml
    - include: repo_setup.yml
    - include: gemset_setup.yml
    - include: hanami_application_setup.yml
