---
#
# http://docs.ansible.com/ansible/git_module.html
# http://docs.ansible.com/ansible/expect_module.html
# http://docs.ansible.com/ansible/get_url_module.html
#

# I'm not able to use git module because I can't type the ssh passphrase
#- name: Clone API repo
#  git: repo=git@github.com:learning-by-making/api.betterlists.io.git dest=~/{{ app_name }} key_file=~/.ssh/id_rsa

- name: Clone API repo
  expect:
    command: git clone git@github.com:learning-by-making/api.betterlists.io.git .
    responses:
      "Enter passphrase for key '/home/vagrant/.ssh/id_rsa': ": "{{ ssh_passphrase }}"
  args:
    chdir: ~/{{ app_name }}
    creates: .git/config

- name: Init Git Flow
  expect:
    command: git flow init
    responses:
      'Branch name for production releases: \[master\] $': ''
      'Branch name for \"next release\" development: \[develop\] $': ''
      'Feature branches\? \[feature/\] $': ''
      'Bugfix branches\? \[bugfix/\] $': ''
      'Release branches\? \[release/\] $': ''
      'Hotfix branches\? \[hotfix/\] $': ''
      'Support branches\? \[support/\] $': ''
      'Version tag prefix\? \[\] $': ''
      'Hooks and filters directory\? \[.*\] $': ''
  args:
    chdir: ~/{{ app_name }}

- name: Git Flow completion
  get_url: url=https://raw.githubusercontent.com/petervanderdoes/git-flow-completion/develop/git-flow-completion.bash dest=/etc/bash_completion.d
  become: yes
