---
#
# https://gist.github.com/maxim/871e611d4bc02c633c67
#

- name: ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: copy host private key to guest VM
  action: template src=templates/id_rsa dest=~/.ssh/id_rsa mode=0600
